In [2]:
import cv2
imgpath = "/home/wazir/ABC/CASIS-OpenCV-Course/Python-OpenCV3/Dataset/mandril_color.tif"
img = cv2.imread(imgpath)
print(img)

[[[ 62 139 166]
  [ 35  48  56]
  [ 26  42  65]
  ...
  [ 50 115 106]
  [ 99 156 141]
  [113 189 171]]

 [[ 50 115 106]
  [ 43 100 139]
  [ 24  24  38]
  ...
  [ 82 132 114]
  [123 155 130]
  [ 57 124 117]]

 [[ 32  64  75]
  [ 48 107 123]
  [ 23  42  50]
  ...
  [ 92  82  98]
  [ 65  83  82]
  [ 40  74  97]]

 ...

 [[161 138 116]
  [129 148 115]
  [132 140 117]
  ...
  [ 49  66  87]
  [ 57  82  92]
  [ 57  75  74]]

 [[170 150 115]
  [158 137 116]
  [131 131 115]
  ...
  [ 66  76  64]
  [ 64  74  74]
  [ 64  57  64]]

 [[170 150 115]
  [158 137 116]
  [131 131 115]
  ...
  [ 66  76  64]
  [ 64  74  74]
  [ 64  57  64]]]


In [4]:
import cv2
imgpath = "/home/wazir/ABC/CASIS-OpenCV-Course/Python-OpenCV3/Dataset/mandril_color.tif"
img = cv2.imread(imgpath)
print(type(img))

<class 'numpy.ndarray'>


# <class 'numpy.ndarray'> it is N dimensional array of composite data type
Numpy = Numerical Python

# uint8 = un signed integer of 8 bits
minimum value = 00000000 in binary, 0x00 hexadecimal, 0 in decimal
maximum vale = 11111111 in binary,  0xFF hexadecimal, 255
so all values less than 255 in image matrix